### ISSUE TITLE
Fix auth-proxy-requirer charmcraft

### ISSUE THREAD

**Issue by natalian98** [canonical/oathkeeper-operator#83]
### Bug Description

The test charm `auth-proxy-requirer` fails to be built since the new charmcraft version release. This causes the CI to fail, see https://github.com/canonical/oathkeeper-operator/actions/runs/10244993325/job/28339107722.

### To Reproduce

Run CI

### Environment

juju 3.4
microk8s 1.28/strict-stable

### Relevant log output

```shell
2024-08-05 08:20:13.132 ::    :: Collecting pydantic-core==2.20.1 (from pydantic)
2024-08-05 08:20:13.143 ::    ::   Downloading pydantic_core-2.20.1.tar.gz (388 kB)
2024-08-05 08:20:13.153 ::    ::      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.4/388.4 kB 56.8 MB/s eta 0:00:00
2024-08-05 08:20:13.227 ::    ::   Installing build dependencies: started
2024-08-05 08:20:19.393 ::    ::   Installing build dependencies: finished with status 'error'
2024-08-05 08:20:19.400 ::    ::   error: subprocess-exited-with-error
2024-08-05 08:20:19.401 ::    ::
2024-08-05 08:20:19.401 ::    ::   × pip subprocess to install build dependencies did not run successfully.
2024-08-05 08:20:19.401 ::    ::   │ exit code: 1
2024-08-05 08:20:19.401 ::    ::   ╰─> [76 lines of output]
2024-08-05 08:20:19.401 ::    ::       Collecting maturin<2,>=1
2024-08-05 08:20:19.401 ::    ::         Downloading maturin-1.7.0.tar.gz (188 kB)
2024-08-05 08:20:19.402 ::    ::            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.3/188.3 kB 8.4 MB/s eta 0:00:00
2024-08-05 08:20:19.402 ::    ::         Installing build dependencies: started
2024-08-05 08:20:19.402 ::    ::         Installing build dependencies: finished with status 'done'
2024-08-05 08:20:19.402 ::    ::         Getting requirements to build wheel: started
2024-08-05 08:20:19.402 ::    ::         Getting requirements to build wheel: finished with status 'done'
2024-08-05 08:20:19.402 ::    ::         Preparing metadata (pyproject.toml): started
2024-08-05 08:20:19.402 ::    ::         Preparing metadata (pyproject.toml): finished with status 'done'
2024-08-05 08:20:19.402 ::    ::       Collecting typing-extensions!=4.7.0,>=4.6.0
2024-08-05 08:20:19.402 ::    ::         Downloading typing_extensions-4.12.2.tar.gz (85 kB)
2024-08-05 08:20:19.403 ::    ::            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.3/85.3 kB 26.6 MB/s eta 0:00:00
2024-08-05 08:20:19.403 ::    ::         Installing build dependencies: started
2024-08-05 08:20:19.403 ::    ::         Installing build dependencies: finished with status 'done'
2024-08-05 08:20:19.403 ::    ::         Getting requirements to build wheel: started
2024-08-05 08:20:19.403 ::    ::         Getting requirements to build wheel: finished with status 'done'
2024-08-05 08:20:19.403 ::    ::         Preparing metadata (pyproject.toml): started
2024-08-05 08:20:19.403 ::    ::         Preparing metadata (pyproject.toml): finished with status 'done'
2024-08-05 08:20:19.404 ::    ::       Collecting tomli>=1.1.0 (from maturin<2,>=1)
2024-08-05 08:20:19.404 ::    ::         Using cached tomli-2.0.1-py3-none-any.whl
2024-08-05 08:20:19.404 ::    ::       Building wheels for collected packages: maturin, typing-extensions
2024-08-05 08:20:19.404 ::    ::         Building wheel for maturin (pyproject.toml): started
2024-08-05 08:20:19.404 ::    ::         Building wheel for maturin (pyproject.toml): finished with status 'error'
2024-08-05 08:20:19.405 ::    ::         error: subprocess-exited-with-error
2024-08-05 08:20:19.405 ::    ::
2024-08-05 08:20:19.405 ::    ::         × Building wheel for maturin (pyproject.toml) did not run successfully.
2024-08-05 08:20:19.405 ::    ::         │ exit code: 1
2024-08-05 08:20:19.405 ::    ::         ╰─> [34 lines of output]
2024-08-05 08:20:19.406 ::    ::             /tmp/pip-build-env-yxd6xrbv/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:79: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
2024-08-05 08:20:19.406 ::    ::               corresp(dist, value, root_dir)
2024-08-05 08:20:19.406 ::    ::             running bdist_wheel
2024-08-05 08:20:19.406 ::    ::             running build
2024-08-05 08:20:19.406 ::    ::             running build_py
2024-08-05 08:20:19.406 ::    ::             creating build
2024-08-05 08:20:19.407 ::    ::             creating build/lib.linux-x86_64-cpython-310
2024-08-05 08:20:19.407 ::    ::             creating build/lib.linux-x86_64-cpython-310/maturin
2024-08-05 08:20:19.407 ::    ::             copying maturin/__init__.py -> build/lib.linux-x86_64-cpython-310/maturin
2024-08-05 08:20:19.407 ::    ::             copying maturin/__main__.py -> build/lib.linux-x86_64-cpython-310/maturin
2024-08-05 08:20:19.407 ::    ::             running egg_info
2024-08-05 08:20:19.407 ::    ::             creating maturin.egg-info
2024-08-05 08:20:19.407 ::    ::             writing maturin.egg-info/PKG-INFO
2024-08-05 08:20:19.407 ::    ::             writing dependency_links to maturin.egg-info/dependency_links.txt
2024-08-05 08:20:19.408 ::    ::             writing requirements to maturin.egg-info/requires.txt
2024-08-05 08:20:19.408 ::    ::             writing top-level names to maturin.egg-info/top_level.txt
2024-08-05 08:20:19.408 ::    ::             writing manifest file 'maturin.egg-info/SOURCES.txt'
2024-08-05 08:20:19.408 ::    ::             reading manifest file 'maturin.egg-info/SOURCES.txt'
2024-08-05 08:20:19.408 ::    ::             reading manifest template 'MANIFEST.in'
2024-08-05 08:20:19.408 ::    ::             warning: no files found matching '*.json' under directory 'src/python_interpreter'
2024-08-05 08:20:19.408 ::    ::             writing manifest file 'maturin.egg-info/SOURCES.txt'
2024-08-05 08:20:19.408 ::    ::             running build_ext
2024-08-05 08:20:19.408 ::    ::             running build_rust
2024-08-05 08:20:19.408 ::    ::             error: can't find Rust compiler
2024-08-05 08:20:19.408 ::    ::
2024-08-05 08:20:19.409 ::    ::             If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
2024-08-05 08:20:19.409 ::    ::
2024-08-05 08:20:19.409 ::    ::             To update pip, run:
2024-08-05 08:20:19.409 ::    ::
2024-08-05 08:20:19.409 ::    ::                 pip install --upgrade pip
2024-08-05 08:20:19.409 ::    ::
2024-08-05 08:20:19.409 ::    ::             and then retry package installation.
2024-08-05 08:20:19.409 ::    ::
2024-08-05 08:20:19.409 ::    ::             If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
2024-08-05 08:20:19.409 ::    ::             [end of output]
2024-08-05 08:20:19.410 ::    ::
2024-08-05 08:20:19.410 ::    ::         note: This error originates from a subprocess, and is likely not a problem with pip.
2024-08-05 08:20:19.410 ::    ::         ERROR: Failed building wheel for maturin
2024-08-05 08:20:19.410 ::    ::         Building wheel for typing-extensions (pyproject.toml): started
2024-08-05 08:20:19.410 ::    ::         Building wheel for typing-extensions (pyproject.toml): finished with status 'done'
2024-08-05 08:20:19.410 ::    ::         Created wheel for typing-extensions: filename=typing_extensions-4.12.2-py3-none-any.whl size=37438 sha256=04e5ca0351e0f3f85c6853954072df659d0d13fac324d0072316b67d7794700d
2024-08-05 08:20:19.410 ::    ::         Stored in directory: /root/.cache/pip/wheels/fe/ad/a8/99c5bcf139f345b732f69da1caea770083939c017f42ec00d8
2024-08-05 08:20:19.410 ::    ::       Successfully built typing-extensions
2024-08-05 08:20:19.410 ::    ::       Failed to build maturin
2024-08-05 08:20:19.410 ::    ::       ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (maturin)
2024-08-05 08:20:19.410 ::    ::
Notice: 05 08:20:19.410 ::    ::       [notice] A new release of pip is available: 24.1.1 -> 24.2
Notice: 05 08:20:19.411 ::    ::       [notice] To update, run: python3 -m pip install --upgrade pip
2024-08-05 08:20:19.411 ::    ::       [end of output]
2024-08-05 08:20:19.411 ::    ::
2024-08-05 08:20:19.411 ::    ::   note: This error originates from a subprocess, and is likely not a problem with pip.
2024-08-05 08:20:19.411 ::    :: error: subprocess-exited-with-error
2024-08-05 08:20:19.411 ::    ::
2024-08-05 08:20:19.411 ::    :: × pip subprocess to install build dependencies did not run successfully.
2024-08-05 08:20:19.411 ::    :: │ exit code: 1
2024-08-05 08:20:19.411 ::    :: ╰─> See above for output.
2024-08-05 08:20:19.411 ::    ::
2024-08-05 08:20:19.411 ::    :: note: This error originates from a subprocess, and is likely not a problem with pip.
2024-08-05 08:20:19.412 ::    ::
Notice: 05 08:20:19.412 ::    :: [notice] A new release of pip is available: 24.1.1 -> 24.2
Notice: 05 08:20:19.412 ::    :: [notice] To update, run: python3 -m pip install --upgrade pip
2024-08-05 08:20:19.554 :: Traceback (most recent call last):
2024-08-05 08:20:19.554 ::   File "/snap/charmcraft/4264/lib/python3.10/site-packages/charmcraft/charm_builder.py", line 480, in <module>
2024-08-05 08:20:19.555 ::     main()
2024-08-05 08:20:19.555 ::   File "/snap/charmcraft/4264/lib/python3.10/site-packages/charmcraft/charm_builder.py", line 475, in main
2024-08-05 08:20:19.555 ::     builder.build_charm()
2024-08-05 08:20:19.555 ::   File "/snap/charmcraft/4264/lib/python3.10/site-packages/charmcraft/charm_builder.py", line 93, in build_charm
2024-08-05 08:20:19.556 ::     self.handle_dependencies()
2024-08-05 08:20:19.556 ::   File "/snap/charmcraft/4264/lib/python3.10/site-packages/charmcraft/charm_builder.py", line 351, in handle_dependencies
2024-08-05 08:20:19.556 ::     self._install_dependencies(staging_venv_dir)
2024-08-05 08:20:19.556 ::   File "/snap/charmcraft/4264/lib/python3.10/site-packages/charmcraft/instrum.py", line 152, in _f
2024-08-05 08:20:19.557 ::     return func(*args, **kwargs)
2024-08-05 08:20:19.557 ::   File "/snap/charmcraft/4264/lib/python3.10/site-packages/charmcraft/charm_builder.py", line 283, in _install_dependencies
2024-08-05 08:20:19.557 ::     _process_run(
2024-08-05 08:20:19.557 ::   File "/snap/charmcraft/4264/lib/python3.10/site-packages/charmcraft/charm_builder.py", line 411, in _process_run
2024-08-05 08:20:19.558 ::     raise RuntimeError(f"Subprocess command {cmd} execution failed with retcode {retcode}")
2024-08-05 08:20:19.558 :: RuntimeError: Subprocess command ['/root/parts/charm/build/staging-venv/bin/pip', 'install', '--no-binary=:all:', '--requirement=requirements.txt', 'pydantic'] execution failed with retcode 1
2024-08-05 08:20:19.650 Failed to run the build script for part 'charm'.
2024-08-05 08:20:19.653 Traceback (most recent call last):
2024-08-05 08:20:19.653   File "/snap/charmcraft/4264/lib/python3.10/site-packages/craft_parts/executor/step_handler.py", line 148, in _builtin_build
2024-08-05 08:20:19.654     _create_and_run_script(
2024-08-05 08:20:19.654   File "/snap/charmcraft/4264/lib/python3.10/site-packages/craft_parts/executor/step_handler.py", line 461, in _create_and_run_script
2024-08-05 08:20:19.654     subprocess.run(
2024-08-05 08:20:19.654   File "/snap/charmcraft/4264/usr/lib/python3.10/subprocess.py", line 526, in run
2024-08-05 08:20:19.654     raise CalledProcessError(retcode, process.args,
2024-08-05 08:20:19.654 subprocess.CalledProcessError: Command '[PosixPath('/root/parts/charm/run/build.sh')]' returned non-zero exit status 1.
2024-08-05 08:20:19.654 
2024-08-05 08:20:19.654 The above exception was the direct cause of the following exception:
2024-08-05 08:20:19.655 Traceback (most recent call last):
2024-08-05 08:20:19.655   File "/snap/charmcraft/4264/lib/python3.10/site-packages/craft_application/services/lifecycle.py", line 261, in run
2024-08-05 08:20:19.655     aex.execute(action, stdout=stream, stderr=stream)
2024-08-05 08:20:19.655   File "/snap/charmcraft/4264/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 327, in execute
2024-08-05 08:20:19.655     self._executor.execute(actions, stdout=stdout, stderr=stderr)
2024-08-05 08:20:19.655   File "/snap/charmcraft/4264/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 137, in execute
2024-08-05 08:20:19.655     self._run_action(act, stdout=stdout, stderr=stderr)
2024-08-05 08:20:19.655   File "/snap/charmcraft/4264/lib/python3.10/site-packages/craft_parts/executor/executor.py", line 214, in _run_action
2024-08-05 08:20:19.655     handler.run_action(action, stdout=stdout, stderr=stderr)
2024-08-05 08:20:19.655   File "/snap/charmcraft/4264/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 170, in run_action
2024-08-05 08:20:19.655     state = handler(step_info, stdout=stdout, stderr=stderr)
2024-08-05 08:20:19.655   File "/snap/charmcraft/4264/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 309, in _run_build
2024-08-05 08:20:19.655     self._run_step(
2024-08-05 08:20:19.656   File "/snap/charmcraft/4264/lib/python3.10/site-packages/craft_parts/executor/part_handler.py", line 491, in _run_step
2024-08-05 08:20:19.656     return step_handler.run_builtin()
2024-08-05 08:20:19.656   File "/snap/charmcraft/4264/lib/python3.10/site-packages/craft_parts/executor/step_handler.py", line 108, in run_builtin
2024-08-05 08:20:19.656     return handler()
2024-08-05 08:20:19.656   File "/snap/charmcraft/4264/lib/python3.10/site-packages/craft_parts/executor/step_handler.py", line 157, in _builtin_build
2024-08-05 08:20:19.656     raise errors.PluginBuildError(
2024-08-05 08:20:19.656 craft_parts.errors.PluginBuildError: Failed to run the build script for part 'charm'.
```

**Comment by natalian98** [comment]
This issue was resolved by a new charmcraft release.
